<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Casia_backend.src.Auth.API</RootNamespace>
    <UserSecretsId>620d5662-aecd-4f1a-be1e-de45c7069b9d</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.24.1-preview.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Casia-backend.src.Auth.Core.Domain\Casia-backend.src.Auth.Core.Domain.csproj" />
    <ProjectReference Include="..\Casia-backend.src.Shared\Casia-backend.src.Shared.csproj" />
  </ItemGroup>

</Project>
